Ft/isa l
scality/eclib pull request #38
Opened 2016-11-09 16:18 UTC by lamphamsy

Add isa-l backends

2016-11-21 18:35 UTC, rahulreddy approved these changes

2016-11-22 09:46 UTC, ghost requested changes
Two nits and a concern.

2016-11-22 09:46 UTC, michael-zapata commented on Makefile
> +	git clone git@github.com:lamphamsy/gf-complete.git $@
We can forego this.

2016-11-22 09:46 UTC, michael-zapata commented on Makefile
> +	git clone git@github.com:lamphamsy/jerasure.git $@
As well as this.

2016-11-22 09:46 UTC, michael-zapata commented on test/functional/functest.js
> -// The tests with ISA require an additional library. They are disabled for now because of this.
If you added the backend, doesn't it make sense to activate them instead?

In any case, some tests would be welcome here.

2016-11-22 10:05 UTC, lamphamsy commented on test/functional/functest.js
> -// The tests with ISA require an additional library. They are disabled for now because of this.
Yes, I forgot to delete these comments. An example for isa-l is added.

2017-11-24 10:07 UTC, lamphamsy commented
Merge to working branch

2017-11-24 10:08 UTC, merged